### ISSUE TITLE
Variable ZSH_CUSTOM doesn't appear to be set

### ISSUE THREAD

**Issue by Minky-j** [thelioncape/ZSH-Setup-Scripts#1]
When running setup.sh, an ZSH_CUSTOM is not set.
This causes the script to try and write "bullet-train.zsh-theme" to the root directory, which causes breakage

Code added to test:
![image](https://user-images.githubusercontent.com/22060245/90991172-b9021d00-e596-11ea-9c29-b1fc480d7f82.png)

![image](https://user-images.githubusercontent.com/22060245/90991164-aa1b6a80-e596-11ea-86c8-4f4043755179.png)

Problem occurs here:
![image](https://user-images.githubusercontent.com/22060245/90991185-d636eb80-e596-11ea-8f7d-44371ac05b83.png)

**Comment by Minky-j** [comment]
The rest of the script needs to be run inside a ZSH shell, but by default it is run in bash:
![image](https://user-images.githubusercontent.com/22060245/90991248-34fc6500-e597-11ea-8d37-4d3705f2dc14.png)

**Comment by Minky-j** [comment]
This change worked in my own private testing, but I couldn't test it in this script because of issues like #2 

Although F for anyone who uses a different $ZSH_CUSTOM

**Comment by thelioncape** [comment]
See #2 
Issue resolved
