### ISSUE TITLE
Script Doesn't actually install ohmyzsh

### ISSUE THREAD

**Issue by Minky-j** [thelioncape/ZSH-Setup-Scripts#2]
when running setup.sh, it doesn't run the ohmyzsh install script it downloads, instead it is simply outputted to the console.

![image](https://user-images.githubusercontent.com/22060245/90991358-1ea2d900-e598-11ea-9bb5-c6333b71fd64.png)

**Comment by Minky-j** [comment]
![image](https://user-images.githubusercontent.com/22060245/90991485-f5cf1380-e598-11ea-929e-298a3aca39b5.png)

**Comment by thelioncape** [comment]
Updated script to run the unattended version of the oh-my-zsh install. Should fix issue
https://github.com/thelioncape/ZSH-Setup-Scripts/commit/205cfed9a2d40a24c98ea4182d321795dc9ab653
