### ISSUE TITLE
sed command doesn't work

### ISSUE THREAD

**Issue by Minky-j** [thelioncape/ZSH-Setup-Scripts#3]
sed -i "s/^ZSH_THEME=.*^/ZSH_THEME=\"bullet-train\"/" $HOME/.zshrc

Doesn't change anything in .zshrc even after an install

**Comment by thelioncape** [comment]
Fix might be to change command like so:
sed -i "s/^ZSH_THEME=.*^/ZSH_THEME="bullet-train"/" $HOME/.zshrc
sed -i "s/^ZSH_THEME=.*$/ZSH_THEME="bullet-train"/" $HOME/.zshrc

Don't have time to fix this today. Maybe you could create a PR?

**Comment by thelioncape** [comment]
Fix might be to change command like so:
sed -i "s/^ZSH_THEME=.^/ZSH_THEME="bullet-train"/" $HOME/.zshrc
sed -i "s/^ZSH_THEME=.$/ZSH_THEME="bullet-train"/" $HOME/.zshrc

Don't have time to fix this today. Maybe you could create a PR @Minky-j ?

**Comment by Minky-j** [comment]
It may be worth noting that the fixes suggested above also don't appear to make any changes.

I'll try and make a PR
