### ISSUE TITLE
Necessary fonts are not installed by setup.sh

### ISSUE THREAD

**Issue by Minky-j** [thelioncape/ZSH-Setup-Scripts#4]
This script works great on Kali, which has the fonts installed by default, but doesn't work on OS's with the fonts missing.

Might want to modify the install script to also install the necessary fonts

![image](https://user-images.githubusercontent.com/22060245/90991586-dab0d380-e599-11ea-9e15-319b0dc53ad2.png)

**Comment by thelioncape** [comment]
Need to add requirement to install powerline-patched font
